spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_app
    username: springstudent
    password: springstudent

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  mvc:
    converters:
      preferred-json-mapper: jackson
